# Create a Jekyll container for GitHub Pages
# See this for current supported versions: https://pages.github.com/versions/
FROM ruby:3.3

# Update the Ruby bundler
RUN gem update bundler 

# Install Bundler and Jekyll
RUN gem install bundler jekyll 