name: E2E CI/CD (caller)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      dotnet-version: '10.0.x'
      configuration: 'Release'
      run-tests: true
      start-docker: true
      wait-url: 'http://localhost:5106'

  call-e2e:
    needs: call-build
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      node-version: '20'
      playwright-install: true
      e2e-tests-path: 'tests/E2ETests'
      app-url: 'http://localhost:5106'
